### PR TITLE
Escape CSRF token before sending during oauth flow

### PR DESCRIPTION
**Pull request by christopherjwang**
Base64 might contain +'s, which can cause a web framework to decode the plus as a space on the redirect, which can cause various CRSF token mismatch errors

I run into this error every once in a while:
```
#<DropboxOAuth2Flow::CsrfError: Expected "5i1a6SIc7qKE4cx35F+6Lg==", got "5i1a6SIc7qKE4cx35F 6Lg==".>
```

Other times, the oauth flow completes successfully.

Does this change have other implications?

### CODE REVIEW

**Comment by cakoose** [comment]
I'm not sure why this is broken.  We pass the value to `_get_authorize_url`, which then passes it to `make_query_string`, which calls `CGI.escape`.  Am I missing something?

**Comment by cakoose** [comment]
What are you doing with the URL you get back from `start()`?  Maybe you're using it in a place that requires additional escaping?

For example, anything URLs you put in an HTML document should be escaped according to HTML's escaping rules.  Sometimes the web framework's templating library will handle the escaping, but not always.

**Comment by cakoose** [comment]
Also, BTW, this SDK is deprecated.
1. The code is no longer being maintained.
2. It uses Dropbox API v1, which has been deprecated and will eventually stop working.

Here are couple Ruby SDKs that use Dropbox API v2:
- https://github.com/Jesus/dropbox_api
- https://github.com/waits/dropbox-sdk-ruby

**Comment by christopherjwang** [comment]
This is the issue I'm running into:

That the URL from start is a link that will put them into the oauth flow. I'm not doing anything special there.

So an example response from the `start` method might be (in current master):
```
https://www.dropbox.com/1/oauth2/authorize?client_id=7x1q6f461ic06sx&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3002%2Fent%2Fsources%2Fdropbox%2Fcreate&state=Ryl2FFjs7WtYlLq%2Bj2HFVw%3D%3D%7C%7B%22action%22%3A%22create%22%7D
```

which escaped is:

```
"https://www.dropbox.com/1/oauth2/authorize?client_id=7x1q6f461ic06sx&response_type=code&redirect_uri=http://localhost:3002/ent/sources/dropbox/create&state=Ryl2FFjs7WtYlLq+j2HFVw==|{\"action\":\"create\"}"
```

pulling out the relevant parameter (redirect_uri)
```
http://localhost:3002/ent/sources/dropbox/create&state=Ryl2FFjs7WtYlLq+j2HFVw==|[...]
```

which leads to the state value:
```
Ryl2FFjs7WtYlLq+j2HFVw==
```

Won't that `+` be parsed as a space? Or is this a rails specific thing?

I'll also take a look at the other libraries. I had no idea this was deprecated!

**Comment by cakoose** [comment]
This is the URL returned by `start()`, broken down to show the query parameters:

```
https://www.dropbox.com/1/oauth2/authorize
    ?client_id=7x1q6f461ic06sx&response_type=code
    &redirect_uri=http%3A%2F%2Flocalhost%3A3002%2Fent%2Fsources%2Fdropbox%2Fcreate
    &state=Ryl2FFjs7WtYlLq%2Bj2HFVw%3D%3D%7C%7B%22action%22%3A%22create%22%7D
```

I'm not sure what you mean by "which escaped is".  You seem to be de-escaping the URL before extracting the `redirect_uri` parameter.  As a result, the `state` parameter gets inadvertently merged in.  That's not what the Dropbox authorization endpoint does.

The Dropbox authorization endpoint maintains them as two separate parameters and then combines them with correct escaping, which should result in something like:

The Dropbox authorization endpoint should redirect back to your app with a URL like:
```
http://localhost:3002/ent/sources/dropbox/create&state=Ryl2FFjs7WtYlLq%2Bj2HFVw%3D%3D%7C%7B%22action%22%3A%22create%22%7D
```

What exactly are you doing?  Are you following the Rails 3 example in `examples/dropbox_controller.rb`?

**Comment by christopherjwang** [comment]
Hey, thanks for your help with this! This isn't an issue with the SDK.

**Pull request closed without merging**
