### PR TITLE
Style checks as ruby convention

### PR DESCRIPTION
**Pull request by yatish27**
* Indents hash params
* Replace with explicit defs with `attr_reader`

### CODE REVIEW

**Comment by yatish27** [comment]
Made changes as per suggestions

**Comment by cakoose** [comment]
Can you also undo the hash/assignment alignment changes?

**Comment by yatish27** [comment]
Reverted the hash changes and squashed the commits

**Comment by cakoose** [comment]
Committed in c98f97c9d986eab9f93262c14763bd0c710024f5

Thanks.

**Pull request closed without merging**
